Need to specify types for collection assignment
Fixes:

fms_mo/aiu_addons/i8i8/i8i8_aiu_adapter.py:66: error: Unsupported target for indexed assignment ("Mapping[str, Any]")  [index]
fms_mo/aiu_addons/i8i8/i8i8_aiu_adapter.py:67: error: Unsupported target for indexed assignment ("Mapping[str, Any]")  [index]
fms_mo/aiu_addons/i8i8/i8i8_aiu_adapter.py:75: error: Unsupported target for indexed assignment ("Mapping[str, Any]")  [index]
fms_mo/aiu_addons/i8i8/i8i8_aiu_adapter.py:82: error: Unsupported target for indexed assignment ("Mapping[str, Any]")  [index]
fms_mo/aiu_addons/i8i8/i8i8_aiu_adapter.py:87: error: Unsupported target for indexed assignment ("Mapping[str, Any]")  [index]

fms_mo/quant/quantizers.py:4161: error: Incompatible types in assignment (expression has type "list[int]", variable has type "None")  [assignment]
fms_mo/quant/quantizers.py:4161: error: Argument 1 to "len" has incompatible type "None"; expected "Sized"  [arg-type]
fms_mo/quant/quantizers.py:4162: error: Unsupported target for indexed assignment ("None")  [index]
fms_mo/quant/quantizers.py:4162: error: Value of type "None" is not indexable  [index]

Signed-off-by: Martin Hickey <martin.hickey@ie.ibm.com>